[package]
name = "uuidgen"
version = "0.1.0"
edition = "2021"

[dependencies.uuid]
version = "1.6.1"
features = [
         "std",
         "v3",
         "v4",
         "v5",
         "v6",
         "v7"
         ]
